version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tp3-mysql

    # variables should be changed to docker secrets (similar to .env variables) 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_passwords
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword 

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
  
  # other potential services:
  # Redis
  # This java app but builded in a web type of docker app
  # web frontend dockerized app
  # 
volumes:
  mysql_data: